Repository lhfbc/iri-regression-tests, pull requests merged in 2019-04, with the labels that each got.

#28 [fix #3] add config file of travis-ci
  .travis.yml
  cli.py
  common.py
  start_and_stop_a_node.sh
Labels: enhancement

#31 Cherry pick v0.1.1
  .travis.yml
  10_send_utxo_transactions_two_nodes_with_batch.sh
  9_send_utxo_transactions_two_nodes_without_batch.sh
  cli.py
  common.py
  failover_test_txn_count.py
  run_all_stable_tests.sh
  start_and_stop_a_node.sh
Labels: duplicate

#34 [fix #32] change the branch of iri from dev to v0.2-streamnet
  .travis.yml
Labels: bug

#33 [fix #32] change the branch of iri from dev to v0.1-streamnet
  .travis.yml
Labels: bug
