Repository lhfbc/iri-regression-tests, pull requests merged in 2019-02, with the labels that each got.

#6 [fix #4 #5] refactor test cases and add 3 more test cases.
  4_send_transactions_with_ipfs_without_batch_without_compression-testnet.sh
  4_send_transactions_without_batch_without_database-testnet.sh
  5_send_transactions_with_batch_without_database-testnet.sh
  5_send_transactions_with_ipfs_with_batch_without_compression-testnet.sh
  6_send_transactions_without_ipfs_without_bach_without_compression-testnet.sh
  7_send_transactions_without_ipfs_with_bach_without_compression-testnet.sh
  8_send_transactions_without_ipfs_with_bach_with_compression-testnet.sh
  cli.py
  common.py
  put_cache.py
  put_file.py
  run_all_stable_tests.sh
  start_and_stop_a_node.sh
Labels: bug, enhancement

#9 [fix #8] change format of content in put_file & put_cache.
  6_send_transactions_without_ipfs_without_bach_without_compression-testnet.sh
  7_send_transactions_without_ipfs_with_bach_without_compression-testnet.sh
  8_send_transactions_without_ipfs_with_bach_with_compression-testnet.sh
  common.py
Labels: bug

#10 [ifx #8] Change tx content
  common.py
Labels: bug

#11 add statement to set ipfs to 'false', and modify some waiting durations.
  common.py
  start_and_stop_a_node.sh
Labels: enhancement

#14 [fix #13] change git repo from iotaledger to wunder3605
  0_clone_and_build_jar.sh
Labels: bug

#18 cherry pick [fix #15] Add tag
  .gitignore
  common.py
Labels: duplicate
